Feature/bg 13
CodersCampLittleDevs/CodersCamp2021-ProjectWebDevelopmentBasics-Battleship-Game pull request #16
Opened 2021-12-16 11:36 UTC by MaciekPon

feat(settings): 
- add responsive styles for settings page

2021-12-16 22:09 UTC, ruljin requested changes

2021-12-16 22:09 UTC, ruljin commented on src/settings/settings.scss
> +}
Like we discussed on Discord - there is a bit to change in styles like missing font-weights, colors, paddings/margins, cursor on the button, etc.

2021-12-17 07:52 UTC, JustD1d1t commented on src/settings/settings.scss
> +  width: calc(100% - 30vw);
Why using calc instead 70vw?

2021-12-17 07:52 UTC, JustD1d1t commented on src/settings/settings.scss
> +    height: 71px;
You could use 70px :D

2021-12-17 07:52 UTC, JustD1d1t commented on src/settings/settings.scss
> +    width: 101px;
same as up

2021-12-18 11:23 UTC, ruljin approved these changes

2021-12-18 13:17 UTC, merged