update highscores.js and style of the main page
CodersCampLittleDevs/CodersCamp2021-ProjectWebDevelopmentBasics-Battleship-Game pull request #30
Opened 2021-12-30 14:23 UTC by alicjaguzik

2021-12-31 19:32 UTC, ruljin requested changes

2021-12-31 19:32 UTC, ruljin commented on src/index.scss
> -.logo {
Styles for mobile version `360 x 640` are different than the one on Figma.

2021-12-31 19:32 UTC, ruljin commented on src/index.scss
> -.logo {
Same for `1440 x 1024` for the main page.

2021-12-31 19:32 UTC, ruljin commented on src/index.scss
> -.logo {
High scores for mobile version `360 x 640` are different than the one on Figma.

2022-01-02 15:01 UTC, JustD1d1t commented on src/variables.scss
> +$s-breakpoint: 360px;
why we need variable with this resolution?
In my opinion we should start styling views from mobile to desktop (mobile first). I think that users on watches etc will not play this game.

2022-01-04 16:49 UTC, merged